# Generated by Django 2.1 on 2018-08-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_id',
        ),
    ]
