# Generated by Django 2.1 on 2018-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0003_auto_20180818_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='hwd',
            field=models.IntegerField(default=0),
        ),
    ]
