# Generated by Django 2.1 on 2018-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0004_auto_20180818_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='teacher_id',
            field=models.IntegerField(default=0),
        ),
    ]
