# Generated by Django 2.1 on 2018-10-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0005_progress_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionForContactId', models.IntegerField()),
                ('notes', models.CharField(max_length=1000)),
                ('dueDate', models.DateField()),
                ('actioned', models.BooleanField()),
                ('actionedByContactId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('emailId', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('parentContactId', models.IntegerField()),
                ('contactTypeId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgressForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressEntryTypeId', models.IntegerField()),
                ('staffContactId', models.IntegerField()),
                ('notes', models.CharField(max_length=1000)),
                ('studentContactId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows_progress_of', to='progress_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=200)),
                ('schoolYear', models.IntegerField()),
                ('birthday', models.DateField()),
                ('contactId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_information_in', to='progress_app.Contact')),
            ],
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='progress',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
        migrations.AddField(
            model_name='actionrequired',
            name='staffContactId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_raised_by', to='progress_app.Contact'),
        ),
    ]
